In [4]:
import numpy as np
a=np.array([0,1,2,3]) #一个向量
b=np.array([4,5,6,7]) #另一个向量
c=np.array([[0,1,2,3],#一个矩阵
           [4,5,6,7]])

d=np.zeros((2,4))     #2*4的全零矩阵
e=np.random.rand(2,5) #2*5的随机矩阵，元素的值在0到1之间

print(a)
print()

print(b)
print()

print(c)
print()

print(d)
print()

print(e)

[0 1 2 3]

[4 5 6 7]

[[0 1 2 3]
 [4 5 6 7]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0.57098209 0.13800791 0.7065916  0.77809562 0.8438687 ]
 [0.8953357  0.66488207 0.00939334 0.10181642 0.09276199]]
